apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-java-21
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "apache/spark:4.0.0-preview2-scala2.13-java21-ubuntu"
  imagePullPolicy: Always
  mainClass: learning.apache.spark.SparkCode
  mainApplicationFile: "local:///mnt/spark/work/spark-template-java-21.jar"
  sparkVersion: "4.0.0-preview2"
  restartPolicy:
    type: Never
  volumes:
    - name: test-volume
      hostPath:
        path: "/minikube-host"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      app: spark
      version: 4.0.0-preview2
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      app: spark
      version: 4.0.0-preview2
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
