apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-java-17
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "apache/spark:3.5.3-scala2.12-java17-ubuntu"
  imagePullPolicy: Always
  mainClass: learning.apache.spark.SparkCode
  mainApplicationFile: "local:///mnt/spark/work/spark-template-java-17.jar"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  volumes:
    - name: test-volume
      hostPath:
        path: "/minikube-host"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      app: spark
      version: 3.5.3
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      app: spark
      version: 3.5.3
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
