apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-java-17
  namespace: default
spec:
  type: Java
  mode: cluster
  image: "apache/spark:3.5.3-scala2.12-java17-ubuntu"
  imagePullPolicy: Always
  mainClass: learning.apache.spark.template.SparkCodeAdvanced
  mainApplicationFile: "local:///mnt/spark/work/spark-template-java-17.jar"
  arguments:
    - "--input=/mnt/spark/work/data/app_data.log"
  sparkConf:
    spark.driver.extraClassPath: "/mnt/spark/work/libs/*"
    spark.executor.extraClassPath: "/mnt/spark/work/libs/*"
    spark.driver.extraJavaOptions: "-Dlog4j.configurationFile=/mnt/spark/work/logs/driver/log4j2.xml"
    spark.executor.extraJavaOptions: "-Dlog4j.configurationFile=/mnt/spark/work/logs/executor/log4j2.xml"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  volumes:
    - name: test-volume
      hostPath:
        path: "/minikube-host"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    labels:
      app: spark
      version: 3.5.3
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
  executor:
    cores: 1
    instances: 2
    memory: "1g"
    labels:
      app: spark
      version: 3.5.3
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/spark/work
